---
:common:
  :worker_log: worker.log
  :ingester_log: ingester.log

:solr: &solr_common
  # development
  url: http://localhost:8983/solr/development
  # staging
  # url: http://10.0.0.20:8080/solr/hcsvlab
  # production
  # url: http://10.0.0.7:8080/solr/hcsvlab

:rabbitmq: &rabbitmq_common
  :client_class: Bunny
  :error_queue: error
  # development
  :host: 127.0.0.1
  # staging
  #:host: 127.0.0.1
  # production
  #:host: 10.0.0.14
  :port: 5672
  # production
  # :port: 5673
  :vhost: /alveo
  :exchange: 'alveo.workers'
  :prefetch: 1000

:sesame_worker:
  # development
  :base_url: http://localhost:8983/openrdf-sesame/
  # staging
  #:base_url: http://10.0.0.26:8080/openrdf-sesame/
  # production
  #:base_url: http://10.0.0.11:8080/openrdf-sesame/
  :client_class: SesameClient
  :work_queue: sesame
  :paths:
    :repositories: repositories
    :system: repositories/SYSTEM/statements
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: sesame
    :user: sesame
    :pass: sesame
  :batch:
    :enabled: true
    :size: 5000
    :timeout: 180

:solr_worker:
  # development
  :url: http://localhost:8983/solr/development
  # staging
  #:url: http://10.0.0.20:8080/solr/hcsvlab
  # production
  #:url: http://10.0.0.7:8080/solr/hcsvlab

  :client_class: RSolr
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: solr
    :user: solr
    :pass: solr
  :batch:
    :enabled: true
    :size: 10000
    :timeout: 180

:upload_worker:
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: upload
    :user: upload
    :pass: upload
  :solr:
    <<: *solr_common
  :solr_queue: solr
  :sesame_queue: sesame
  :postgres_queue: postgres

:postgres_worker:
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: postgres
    :user: postgres
    :pass: postgres
  :activerecord:
    :adapter: postgresql
    :database: hcsvlab
    :username: hcsvlab
    :password: hcsvlab
    # development
    :host: 127.0.0.1
    # staging
    #:host: 127.0.0.1
    # production
    #:host: 10.0.0.13
  :batch:
    :enabled: true
    :size: 5000
    :timeout: 180

:ingester:
  <<: *rabbitmq_common
  :user: ingester
  :pass: ingester
  :upload_queue: upload
  :sesame_queue: sesame
  :monitor:
    - postgres
    - solr
    - sesame
    - upload
  :monitor_poll: 300


# Specifies the number of processes to launch for each worker.
# The total number of processes shouldn't exceed the number of 
# CPU cores
:worker_launcher:
  :upload_worker:
    :processes: 1
  :solr_worker:
    :processes: 1
  :sesame_worker:
    :processes: 2
  :postgres_worker:
    :processes: 1
