---
:solr: &solr_common
  # :url: http://alveo-qa-solr.intersect.org.au:8080/solr/hcsvlab # Duplicate field, refactor
  :url: http://127.0.0.1:8080/solr/hcsvlab # Duplicate field, refactor

:rabbitmq: &rabbitmq_common
  :client_class: Bunny
  :error_queue: error
  # :host: alveo-qa-mq.intersect.org.au
  # :host: 127.0.0.1
  :vhost: /alveo
  :exchange: 'alveo.workers'

:sesame_worker:
  # :base_url: http://alveo-qa-sesame.intersect.org.au:8080/openrdf-sesame/
  :base_url: http://localhost:8080/openrdf-sesame/
  :client_class: SesameClient
  :work_queue: sesame
  :paths:
    :repositories: repositories
    :system: repositories/SYSTEM/statements
  :rabbitmq:
        <<: *rabbitmq_common
        :work_queue: sesame
        :user: sesame
        :pass: sesame

:solr_worker:
  # :url: http://alveo-qa-solr.intersect.org.au:8080/solr/hcsvlab
  :url: http://localhost:8080/solr/hcsvlab
  :client_class: RSolr
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: solr
    :user: solr
    :pass: solr

:upload_worker:
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: upload # change work_queue to consumption_queue
    :user: upload
    :pass: upload
  :solr:
    <<: *solr_common
  :solr_queue: solr
  :sesame_queue: sesame
  :postgres_queue: postgres

:postgres_worker:
  :rabbitmq:
    <<: *rabbitmq_common
    :work_queue: postgres
    :user: postgres
    :pass: postgres
  :activerecord:
    :adapter: postgresql
    :database: hcsvlab
    :user: hcsvlab
    :host: localhost

:ingester:
  <<: *rabbitmq_common
  :error_log: ingester_errors.log
  :user: ingester
  :pass: ingester
  :upload_queue: upload
  :sesame_queue: sesame