---

solr:
  rdf_relation_to_facet_map:
    'dcterms:isPartOf': collection_name_facet
    'ausnc:mode': AUSNC_mode_facet
    'ausnc:speech_style': AUSNC_speech_style_facet
    'ausnc:publication_status': AUSNC_publication_status_facet
    'ausnc:written_mode': AUSNC_written_mode_facet
    'ausnc:interactivity': AUSNC_interactivity_facet
    'ausnc:communication_context': AUSNC_communication_context_facet
    'ausnc:communication_medium': AUSNC_communication_medium_facet
    'ausnc:communication_setting': AUSNC_communication_setting_facet
    'ausnc:audience': AUSNC_audience_facet
    'olac:discourse_type': OLAC_discourse_type_facet
    'olac:language': OLAC_language_facet
  rdf_ns_to_solr_prefix_map:
    'http://ns.ausnc.org.au/schemas/ace/': ACE_
    'http://ns.ausnc.org.au/schemas/ausnc_md_model/': AUSNC_
    'http://ns.ausnc.org.au/schemas/austlit/': AUSTLIT_
    'http://ns.ausnc.org.au/schemas/cooee/': COOEE_
    'http://ns.ausnc.org.au/schemas/gcsause/': GCSAUSE_
    'http://ns.ausnc.org.au/schemas/ice/': ICE_
    'http://purl.org/dc/terms/': DC_
    'http://purl.org/dc/elements/1.1/': DC_
    'http://purl.org/ontology/bibo/': PURL_BIBO_
    'http://purl.org/vocab/bio/0.1/':  PURL_VOCAB_
    'http://www.language-archives.org/OLAC/1.1/': OLAC_
    'http://xmlns.com/foaf/0.1/': FOAF_
    'http://www.w3.org/1999/02/22-rdf-syntax-ns#': RDF_
    'http://www.loc.gov/loc.terms/relators/': LoC_
    'http://alveo.edu.au/vocabulary/': AUSTALK_
    'http://ns.austalk.edu.au/': Alveo_
